export const userConstants = {
    REGISTER_REQUEST: 'REGISTER_REQUEST',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',

    LOGIN_REQUEST: 'LOGIN_REQUEST',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    
    LOGOUT: 'LOGOUT',

    GET_HISTORY_REQUEST: 'GET_HISTORY_REQUEST',
    GET_HISTORY_SUCCESS: 'GET_HISTORY_SUCCESS',
    GET_HISTORY_FAILURE: 'GET_HISTORY_FAILURE',

    ADD_BOOKING_REQUEST: 'ADD_BOOKING_REQUEST',
    ADD_BOOKING_SUCCESS: 'ADD_BOOKING_SUCCESS',
    ADD_BOOKING_FAILURE: 'ADD_BOOKING_FAILURE',

    UPDATE_BOOKING_REQUEST: 'UPDATE_BOOKING_REQUEST',
    UPDATE_BOOKING_SUCCESS: 'UPDATE_BOOKING_SUCCESS',
    UPDATE_BOOKING_FAILURE: 'UPDATE_BOOKING_FAILURE',

    DELETE_BOOKING_REQUEST: 'DELETE_BOOKING_REQUEST',
    DELETE_BOOKING_SUCCESS: 'DELETE_BOOKING_SUCCESS',
    DELETE_BOOKING_FAILURE: 'DELETE_BOOKING_FAILURE',
    
    GET_USER_PROFILE_DATA_REQUEST: 'GET_USER_PROFILE_DATA_REQUEST',
    GET_USER_PROFILE_DATA_SUCCESS: 'GET_USER_PROFILE_DATA_SUCCESS',
    GET_USER_PROFILE_DATA_FAILURE:  'GET_USER_PROFILE_DATA_FAILURE'
}